const titoli = ['Il grande Lebowski', 
                'Druk', 
                'Sound of metal', 
                'Amores Perros', 
                'Il divo', 
                "Rosemary's Baby", 
                'Funny Games', 
                'Il Padrino', 
                'Il Padrino - Parte II'];
const immagini = ['https://www.cinefacts.it/foto/h!lebowski.cinefacts.jpg', 
                'https://www.ilcineocchio.it/cine/wp-content/uploads/2020/08/Druk.jpg',
                'https://quinlan.it/upload/images/2021/03/Sound-of-metal-2019-Darius-Marder-poster.jpg',
                'https://www.laprensalatina.com/wp-content/uploads/2020/03/amores-perros-7-449x640-1.jpg',
                'https://pad.mymovies.it/filmclub/2008/04/094/locandina.jpg',
                'https://i.pinimg.com/originals/2e/7f/4e/2e7f4e46376a8b0290b2f317ddf00664.jpg',
                'https://images-na.ssl-images-amazon.com/images/I/51z7LDcZfiL.jpg',
                'https://pad.mymovies.it/filmclub/2002/08/056/locandina.jpg',
                'http://aforismi.meglio.it/img/film/Il_Padrino_Parte_II.jpg'];
const info = ['1998 - Ethan & Joel Cohen', 
                '2020 - Thomas Vinterberg',  
                '2019 - Darius Marder',
                '2000 - Alejandro González Iñárritu',
                '2008 - Paolo Sorrentino',
                '1968 - Roman Polański',
                '2007 - Michael Haneke',
                '1972 - Francis Ford Coppola',
                '1974 - Francis Ford Coppola'];